;; Exercise 1.14: Draw the tree illustrating the process generated by the count-change procedure of Section 1.2.2 in making change for 11 cents. What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?
    
(count-change 11)
(cc 11 5)
(+ (cc 11 4) 0)
(+ (+ (cc 11 3) 0) 0)
(+ (+ (+ (cc 11 2) (cc 1 3)) 0) 0)
(+ (+ (+ (+ (cc 11 1) (cc 6 2)) (+ (cc 1 2) 0)) 0) 0)
(+ (+ (+ (+ (+ 0 (cc 10 1)) (+ (cc 6 1) (cc 1 2))) (+ (+ (cc 1 1) 0) 0)) 0) 0)
(+ (+ (+ (+ (+ 0 (+ 0 (cc 9 1))) (+ (+ 0 (cc 5 1)) (+ (+ 0 (cc 0 1)) 0))) (+ (+ (+ 0 (cc 0 1)) 0) 0)) 0) 0)
,,,
(+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (cc 0 1)))))))))))) (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (cc 0 1))))))) (+ (+ 0 (cc 0 1)) 0))) (+ (+ (+ 0 (cc 0 1)) 0) 0)) 0) 0)
(+ (+ (+ (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1))))))))))) (+ (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 (+ 0 1)))))) (+ (+ 0 1) 0))) (+ (+ (+ 0 1) 0) 0)) 0) 0)



;; Order of growth of space is simply to keep track of the depth of the tree, which is the amount to be changed, so the space required is O(n).

;; The umber of steps both appears to be exponential. The complexity increases with the more kinds of coins...(cc n 2) is O(n ^ 2), and (cc n 5) is O(n ^ 5). This is a very inefficient procedure.
